server:
  port: 8090
spring:
  application:
    name: main
  datasource:
    url: jdbc:postgresql://localhost:5432/itracourse
    username: postgres
    password: Israel1997Israel
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-main.xml
  jpa:
    show-sql: true


